[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/air"
  to = "/air.html"
  status = 200

[[redirects]]
  from = "/air/law"
  to = "/air/law.html"
  status = 200

[[redirects]]
  from = "/air/roofing"
  to = "/air/roofing.html"
  status = 200

[[redirects]]
  from = "/air/hvac"
  to = "/air/hvac.html"
  status = 200

[[redirects]]
  from = "/air/pest"
  to = "/air/pest.html"
  status = 200

[[redirects]]
  from = "/air/moving"
  to = "/air/moving.html"
  status = 200

[[redirects]]
  from = "/air/fence"
  to = "/air/fence.html"
  status = 200

[[redirects]]
  from = "/air/garage"
  to = "/air/garage.html"
  status = 200

[[redirects]]
  from = "/air/restoration"
  to = "/air/restoration.html"
  status = 200

[[redirects]]
  from = "/air/electrical"
  to = "/air/electrical.html"
  status = 200

[[redirects]]
  from = "/air/plumbing"
  to = "/air/plumbing.html"
  status = 200

[[redirects]]
  from = "/air/concrete"
  to = "/air/concrete.html"
  status = 200

[[redirects]]
  from = "/air/paving"
  to = "/air/paving.html"
  status = 200

[[redirects]]
  from = "/air/medspa"
  to = "/air/medspa.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
